{{- if or .Values.sidecar.hmac.keyValue .Values.sidecar.audit.tokenValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phase-barrier.fullname" . }}-secrets
  labels:
    {{- include "phase-barrier.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.sidecar.hmac.keyValue }}
  hmac-key: {{ .Values.sidecar.hmac.keyValue | quote }}
{{- end }}
{{- if .Values.sidecar.audit.tokenValue }}
  audit-token: {{ .Values.sidecar.audit.tokenValue | quote }}
{{- end }}
{{- end }}
