# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhaseBarrierStub:
    """phase-barrier sidecar gRPC 门禁服务（v0.39.0）。
    与 HTTP API（/api/state、/api/advance、/api/test-run、/api/source-change、
    /api/write、/api/exec、/api/verify-evidence、/api/audit）等价；
    拦截与校验语义一致：写入/执行被拒返回 PERMISSION_DENIED，参数非法返回 INVALID_ARGUMENT。

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/GetState',
                request_serializer=sidecar__pb2.GetStateRequest.SerializeToString,
                response_deserializer=sidecar__pb2.StateReply.FromString,
                _registered_method=True)
        self.Advance = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/Advance',
                request_serializer=sidecar__pb2.AdvanceRequest.SerializeToString,
                response_deserializer=sidecar__pb2.AdvanceReply.FromString,
                _registered_method=True)
        self.RecordTestRun = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/RecordTestRun',
                request_serializer=sidecar__pb2.RecordTestRunRequest.SerializeToString,
                response_deserializer=sidecar__pb2.RecordTestRunReply.FromString,
                _registered_method=True)
        self.RecordSourceChange = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/RecordSourceChange',
                request_serializer=sidecar__pb2.SourceChangeRequest.SerializeToString,
                response_deserializer=sidecar__pb2.SourceChangeReply.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/WriteFile',
                request_serializer=sidecar__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=sidecar__pb2.WriteFileReply.FromString,
                _registered_method=True)
        self.ExecCommand = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/ExecCommand',
                request_serializer=sidecar__pb2.ExecCommandRequest.SerializeToString,
                response_deserializer=sidecar__pb2.ExecCommandReply.FromString,
                _registered_method=True)
        self.VerifyEvidence = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/VerifyEvidence',
                request_serializer=sidecar__pb2.VerifyEvidenceRequest.SerializeToString,
                response_deserializer=sidecar__pb2.VerifyEvidenceReply.FromString,
                _registered_method=True)
        self.QueryAudit = channel.unary_unary(
                '/phase_barrier.PhaseBarrier/QueryAudit',
                request_serializer=sidecar__pb2.QueryAuditRequest.SerializeToString,
                response_deserializer=sidecar__pb2.QueryAuditReply.FromString,
                _registered_method=True)


class PhaseBarrierServicer:
    """phase-barrier sidecar gRPC 门禁服务（v0.39.0）。
    与 HTTP API（/api/state、/api/advance、/api/test-run、/api/source-change、
    /api/write、/api/exec、/api/verify-evidence、/api/audit）等价；
    拦截与校验语义一致：写入/执行被拒返回 PERMISSION_DENIED，参数非法返回 INVALID_ARGUMENT。

    """

    def GetState(self, request, context):
        """当前阶段（等价 GET /api/state）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Advance(self, request, context):
        """推进阶段，走完整证据校验（等价 POST /api/advance）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTestRun(self, request, context):
        """上报测试运行结果（等价 POST /api/test-run）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordSourceChange(self, request, context):
        """上报源码/测试变更（等价 POST /api/source-change）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """经门禁写入工作区文件（等价 POST /api/write）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCommand(self, request, context):
        """经门禁执行 shell 命令并自动记录测试摘要（等价 POST /api/exec）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEvidence(self, request, context):
        """校验证据签名清单（等价 GET /api/verify-evidence）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAudit(self, request, context):
        """查询审计日志（等价 GET /api/audit）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhaseBarrierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=sidecar__pb2.GetStateRequest.FromString,
                    response_serializer=sidecar__pb2.StateReply.SerializeToString,
            ),
            'Advance': grpc.unary_unary_rpc_method_handler(
                    servicer.Advance,
                    request_deserializer=sidecar__pb2.AdvanceRequest.FromString,
                    response_serializer=sidecar__pb2.AdvanceReply.SerializeToString,
            ),
            'RecordTestRun': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTestRun,
                    request_deserializer=sidecar__pb2.RecordTestRunRequest.FromString,
                    response_serializer=sidecar__pb2.RecordTestRunReply.SerializeToString,
            ),
            'RecordSourceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSourceChange,
                    request_deserializer=sidecar__pb2.SourceChangeRequest.FromString,
                    response_serializer=sidecar__pb2.SourceChangeReply.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=sidecar__pb2.WriteFileRequest.FromString,
                    response_serializer=sidecar__pb2.WriteFileReply.SerializeToString,
            ),
            'ExecCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCommand,
                    request_deserializer=sidecar__pb2.ExecCommandRequest.FromString,
                    response_serializer=sidecar__pb2.ExecCommandReply.SerializeToString,
            ),
            'VerifyEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEvidence,
                    request_deserializer=sidecar__pb2.VerifyEvidenceRequest.FromString,
                    response_serializer=sidecar__pb2.VerifyEvidenceReply.SerializeToString,
            ),
            'QueryAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAudit,
                    request_deserializer=sidecar__pb2.QueryAuditRequest.FromString,
                    response_serializer=sidecar__pb2.QueryAuditReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phase_barrier.PhaseBarrier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phase_barrier.PhaseBarrier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhaseBarrier:
    """phase-barrier sidecar gRPC 门禁服务（v0.39.0）。
    与 HTTP API（/api/state、/api/advance、/api/test-run、/api/source-change、
    /api/write、/api/exec、/api/verify-evidence、/api/audit）等价；
    拦截与校验语义一致：写入/执行被拒返回 PERMISSION_DENIED，参数非法返回 INVALID_ARGUMENT。

    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/GetState',
            sidecar__pb2.GetStateRequest.SerializeToString,
            sidecar__pb2.StateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Advance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/Advance',
            sidecar__pb2.AdvanceRequest.SerializeToString,
            sidecar__pb2.AdvanceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTestRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/RecordTestRun',
            sidecar__pb2.RecordTestRunRequest.SerializeToString,
            sidecar__pb2.RecordTestRunReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordSourceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/RecordSourceChange',
            sidecar__pb2.SourceChangeRequest.SerializeToString,
            sidecar__pb2.SourceChangeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/WriteFile',
            sidecar__pb2.WriteFileRequest.SerializeToString,
            sidecar__pb2.WriteFileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/ExecCommand',
            sidecar__pb2.ExecCommandRequest.SerializeToString,
            sidecar__pb2.ExecCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/VerifyEvidence',
            sidecar__pb2.VerifyEvidenceRequest.SerializeToString,
            sidecar__pb2.VerifyEvidenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phase_barrier.PhaseBarrier/QueryAudit',
            sidecar__pb2.QueryAuditRequest.SerializeToString,
            sidecar__pb2.QueryAuditReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
